### ISSUE TITLE
name of library

### ISSUE THREAD

**Issue by mrtubisz** [jesusbmx/react-native-pdf-page-image#2]
Hey,
your change that you did 20 hours ago just broke my project builds. You got a typo in your name:
https://www.npmjs.com/package/react-naive-pdf-page-image
it should be react-native-pdf-page-image.

**Comment by jesusbmx** [comment]
> Hey, your change that you did 20 hours ago just broke my project builds. You got a typo in your name: https://www.npmjs.com/package/react-naive-pdf-page-image it should be react-native-pdf-page-image.

Hi, I'll fix it right away.

**Comment by jesusbmx** [comment]
> Hey, your change that you did 20 hours ago just broke my project builds. You got a typo in your name: https://www.npmjs.com/package/react-naive-pdf-page-image it should be react-native-pdf-page-image.

I have solved it

- Remove corrupt dependency from `package.json` file `react-naive-pdf-page-image`
- Delete the `node_modules` folder
- Delete the `package-lock.json` file
- Delete the `Podfile.lock` file

Install the dependency
```sh
npm i react-native-pdf-page-image@0.1.5
```

**Comment by jesusbmx** [comment]
Tests were carried out urging the new version and it works successfully

```sh
npm i react-native-pdf-page-image@0.1.5
```
